/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2019-honda-nsx-78ec2b54b63744d48d037b6e41c5004a
Title: 2019 Honda NSX
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CAR(props) {
  const { nodes, materials } = useGLTF('/2019_honda_nsx.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={3}>
        <group rotation={[0, -Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.NSXColoured_Geo_lodA_NSXColoured_Material1_0.geometry}
            material={materials.NSXColoured_Material1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.NSXColoured_Geo_lodA_NSXPaint_Material1_0.geometry}
            material={materials.NSXPaint_Material1}
          />
        </group>
        <group rotation={[0, -Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.NSXGlass_Geo_lodA_NSXWindow_Material1_0.geometry}
            material={materials.NSXWindow_Material1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.NSXGlass_Geo_lodA_phong1_0.geometry}
            material={materials.phong1}
          />
        </group>
        <group rotation={[0, -Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface1_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface3_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface4_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface5_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface6_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface7_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface8_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface9_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface10_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface11_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface12_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface13_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface14_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface15_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface16_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface17_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface18_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, -0.815]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface19_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface20_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface21_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface22_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface23_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface24_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface25_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface26_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface27_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface28_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface29_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface30_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface31_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface32_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface33_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface34_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface35_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface36_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, -0.801]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface37_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface38_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface39_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface40_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface41_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface42_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface43_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface44_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface45_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface46_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface47_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface48_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface49_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface50_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface51_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface52_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface53_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface54_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[1.29, 0.305, 0.815]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface55_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface56_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface57_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface58_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface59_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface60_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface61_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface62_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface63_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface64_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface65_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface66_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface67_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface68_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface69_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface70_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface71_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface72_NSX_3DWheel1A_Material1_0.geometry}
            material={materials.NSX_3DWheel1A_Material1}
            position={[-1.342, 0.33, 0.801]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
        </group>
        <group rotation={[0, -Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface73_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[1.135, 0.305, -0.824]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface74_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[1.135, 0.305, -0.824]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface75_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[1.135, 0.305, -0.824]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface76_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[1.135, 0.305, -0.824]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface77_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[1.135, 0.305, -0.824]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface78_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[-1.187, 0.33, -0.812]}
            scale={[-1, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface79_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[-1.187, 0.33, -0.812]}
            scale={[-1, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface80_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[-1.187, 0.33, -0.812]}
            scale={[-1, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface81_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[-1.187, 0.33, -0.812]}
            scale={[-1, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface82_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[-1.187, 0.33, -0.812]}
            scale={[-1, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface83_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[1.135, 0.305, 0.824]}
            rotation={[-Math.PI, 0, Math.PI]}
            scale={[-1, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface84_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[1.135, 0.305, 0.824]}
            rotation={[-Math.PI, 0, Math.PI]}
            scale={[-1, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface85_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[1.135, 0.305, 0.824]}
            rotation={[-Math.PI, 0, Math.PI]}
            scale={[-1, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface86_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[1.135, 0.305, 0.824]}
            rotation={[-Math.PI, 0, Math.PI]}
            scale={[-1, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface87_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[1.135, 0.305, 0.824]}
            rotation={[-Math.PI, 0, Math.PI]}
            scale={[-1, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface88_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[-1.187, 0.33, 0.812]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface89_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[-1.187, 0.33, 0.812]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface90_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[-1.187, 0.33, 0.812]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface91_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[-1.187, 0.33, 0.812]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface92_NSXCalliperGloss_Material1_0.geometry}
            material={materials.NSXCalliperGloss_Material1}
            position={[-1.187, 0.33, 0.812]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bodyPaint_Geo_lodA_NSXPaint_Material1_0.geometry}
          material={materials.NSXPaint_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXBadge_Geo_lodA_NSXBadge_Material1_0.geometry}
          material={materials.NSXBadge_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXBase_Geo_lodA_NSXBase_Material1_0.geometry}
          material={materials.NSXBase_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXCarbon1M_Geo_lodA_NSXCarbon1M_Material1_0.geometry}
          material={materials.NSXCarbon1M_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXEngine_Geo_lodA_NSXEngine_Material1_0.geometry}
          material={materials.NSXEngine_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXGrille1_Geo_lodA_NSXGrille1_Material1_0.geometry}
          material={materials.NSXGrille1_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXGrille2_Geo_lodA_NSXGrille2_Material1_0.geometry}
          material={materials.NSXGrille2_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXGrille3_Geo_lodA_NSXGrille3_Material1_0.geometry}
          material={materials.NSXGrille3_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXGrille4_Geo_lodA_NSXGrille4_Material1_0.geometry}
          material={materials.NSXGrille4_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXGrille5_Geo_lodA_NSXGrille5_Material1_0.geometry}
          material={materials.NSXGrille5_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXInterior_Geo_lodA_NSXInterior_Material1_0.geometry}
          material={materials.NSXInterior_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXLight_Geo_lodA_NSXLight_Material1_0.geometry}
          material={materials.NSXLight_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXLightEmissive_Geo_lodA_NSXLightEmissive_Material1_0.geometry}
          material={materials.NSXLightEmissive_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXSeatBelt_Geo_lodA_NSXSeatBelt_Material1_0.geometry}
          material={materials.NSXSeatBelt_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXWindow_Geo_lodA_NSXWindow_Material1_0.geometry}
          material={materials.NSXWindow_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXWindowInside_Geo_lodA_NSXWindow_Material1_0.geometry}
          material={materials.NSXWindow_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXCalliperParking_Rear_L1_NSXCalliperGloss_Material1_0.geometry}
          material={materials.NSXCalliperGloss_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXCalliperParking_Rear_R1_NSXCalliperGloss_Material1_0.geometry}
          material={materials.NSXCalliperGloss_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXCalliperParking_Rear_L_NSXCalliperGloss_Material1_0.geometry}
          material={materials.NSXCalliperGloss_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXCalliperParking_Rear_R_NSXCalliperGloss_Material1_0.geometry}
          material={materials.NSXCalliperGloss_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NSXManufacturerPlate_NSXManufacturerPlate_Material1_0.geometry}
          material={materials.NSXManufacturerPlate_Material1}
          rotation={[0, -Math.PI / 2, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/2019_honda_nsx.glb')
